userprofile_project/profiles/urls.py
from django.urls import path
from profiles.views import profile_list, profile_detail, delete_post, edit_post, update_cover, update_profile_picture

app_name = 'profiles'

urlpatterns = [
    path('', profile_list, name='user_list'),  # ყველა მომხმარებლის სია
    path('<int:pk>/', profile_detail, name='profile_detail'),  # კონკრეტული პროფილი
    path('<int:profile_pk>/delete-post/<int:post_pk>/', delete_post, name='delete_post'),
    path('<int:profile_pk>/edit-post/<int:post_pk>/', edit_post, name='edit_post'),
    path('<int:pk>/update_cover/', update_cover, name='update_cover'),
    path('<int:pk>/update_profile_picture/', update_profile_picture, name='update_profile_picture'),
]

userprofile_project/userprofile_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('profiles.urls', namespace='profiles')),
]

if settings.DEBUG:
    # Serve media files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Serve static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userprofile_project/profiles/models.py
# ჯანგოში ჩაშენებული User მოდელის იმპორტი, რომელსაც to='User'-ით ვერ გამოვიყენებ კავშირებში
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE, verbose_name='User')
    bio = models.TextField(blank=True, verbose_name='Bio')
    phone = models.CharField(max_length=20, blank=True, verbose_name='Phone')
    birth_date = models.DateField(blank=True, null=True, verbose_name='Birth Date')
    gender = models.CharField(max_length=10, blank=True, verbose_name='Gender')
    profession = models.CharField(max_length=60, blank=True, verbose_name='Profession')
    avatar = models.ImageField(upload_to='avatars/', blank=True, verbose_name='Avatar')
    profile_pic = models.ImageField(upload_to='profiles/', blank=True, verbose_name='Profile Picture')
    profile_cover = models.ImageField(upload_to='profiles/cover/', blank=True, verbose_name='Profile Cover')

    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated At')

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        return f"{self.user.username} Profile"


class Post(models.Model):
    profile = models.ForeignKey(to='Profile', related_name='posts', on_delete=models.CASCADE, null=True, blank=True,
                                verbose_name='Profile', )
    image = models.ImageField(upload_to='posts/', blank=True, verbose_name='Post Image')
    caption = models.TextField(blank=True, verbose_name='Caption')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created At')
    likes = models.PositiveIntegerField(default=0, verbose_name='Likes Count')
    comments = models.PositiveIntegerField(default=0, verbose_name='Comments Count')

    is_deleted = models.BooleanField(default=False, verbose_name='Deleted')

    class Meta:
        ordering = ['-created_at']
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return f"{self.profile.user.username} - {self.caption[:30] or 'No caption'}"

userprofile_project/profiles/forms.py
from django import forms

from profiles.models import Post, Profile


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'caption']
        labels = {
            'caption': '',
            'image': 'Photo'
        }
        widgets = {
            'caption': forms.Textarea(
                attrs={'rows': 3, 'placeholder': "What's on your mind?", 'class': 'form-control'})
        }

    def clean(self):
        cleaned_data = super().clean()
        caption = cleaned_data.get('caption')
        image = cleaned_data.get('image')

        if not caption and not image:
            raise forms.ValidationError("Please provide text or upload an image.")
        return cleaned_data


class CoverUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_cover']


class ProfilePictureUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_pic']

userprofile_project/profiles/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from profiles.forms import PostForm, CoverUpdateForm, ProfilePictureUpdateForm
from profiles.models import Profile, Post
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST


def profile_list(request):
    profiles = Profile.objects.select_related('user').all()

    paginator = Paginator(profiles, 8)  # აჩვენე 8 პროფილი თითო გვერდზე
    page_number = request.GET.get('page')  # URL-დან ამოიღებს ?page=2
    page_obj = paginator.get_page(page_number)

    return render(request, template_name='user_list.html', context={'page_obj': page_obj})


from django.contrib import messages  # თუ გინდა შეტყობინება messages-ითაც


def profile_detail(request, pk):
    profile = get_object_or_404(Profile, pk=pk)
    posts = profile.posts.filter(is_deleted=False)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)

        if form.is_valid():
            post = form.save(commit=False)
            post.profile = profile
            post.save()
            return redirect('profiles:profile_detail', pk=pk)
    else:
        form = PostForm()

    return render(request, 'profile_detail.html', {
        'profile': profile,
        'posts': posts,
        'form': form,
    })


# delete_post ფუნქცია
def delete_post(request, profile_pk, post_pk):
    profile = get_object_or_404(Profile, pk=profile_pk)
    post = get_object_or_404(Post, pk=post_pk, profile=profile)

    if request.method == 'POST':
        post.is_deleted = True
        return redirect('profiles:profile_detail', pk=profile_pk)

    return redirect('profiles:profile_detail', pk=profile_pk)


# edit_post ფუნქცია
def edit_post(request, profile_pk, post_pk):
    profile = get_object_or_404(Profile, pk=profile_pk)
    post = get_object_or_404(Post, pk=post_pk, profile=profile)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('profiles:profile_detail', pk=profile_pk)
    else:
        form = PostForm(instance=post)

    posts = profile.posts.all()
    return render(request, 'profile_detail.html', {
        'profile': profile,
        'posts': posts,
        'form': form,
        'edit_mode': True,
        'editing_post': post,
    })


@require_POST
def update_cover(request, pk):
    profile = get_object_or_404(Profile, pk=pk)

    form = CoverUpdateForm(request.POST, request.FILES, instance=profile)
    if form.is_valid():
        form.save()
        messages.success(request, "Cover photo updated!")
    else:
        messages.error(request, "Invalid file.")

    return redirect('profiles:profile_detail', pk=pk)


def update_profile_picture(request, pk):
    profile = get_object_or_404(Profile, pk=pk)

    form = ProfilePictureUpdateForm(request.POST, request.FILES, instance=profile)
    if form.is_valid():
        form.save()
        messages.success(request, "Profile photo updated!")
    else:
        messages.error(request, "Invalid file.")

    return redirect('profiles:profile_detail', pk=pk)

userprofile_project/profiles/templates/profile_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ profile.user.username }}{% endblock %}

{% block content %}
    <div class="profile-detail-container">
        <section class="detail-cover-section">

            <div class="detail-cover-box">
                <img src="{{ profile.profile_cover.url }}?v={{ profile.updated_at|date:'U' }}" alt="Profile Cover"
                     class="detail-profile-cover">
                <button class="edit-cover-btn" onclick="document.getElementById('cover-input').click();">
                    <i class="fa-solid fa-camera"></i>
                    Edit Cover Photo
                </button>

                <form method="post" enctype="multipart/form-data" action="{% url 'profiles:update_cover' profile.pk %}"
                      class="cover-upload-form">
                    {% csrf_token %}
                    <input
                            type="file"
                            name="profile_cover"
                            id="cover-input"
                            accept="image/*"
                            style="display: none;"
                            onchange="if(this.files.length > 0) this.form.submit();"
                    >
                </form>


            </div>

            <div class="detail-overlay">
                <div class="profile-pic-container">
                    <img src="{{ profile.profile_pic.url }}" alt="Profile Picture" class="detail-overlay-picture">
                    <form method="post" enctype="multipart/form-data"
                          action="{% url 'profiles:update_profile_picture' profile.pk %}"
                          class="profile-pic-upload-form">
                        {% csrf_token %}
                        <input
                                type="file"
                                name="profile_pic"
                                id="profile-pic-input"
                                accept="image/*"
                                style="display: none;"
                                onchange="if(this.files.length > 0) this.form.submit();"
                        >
                        <button type="button" class="edit-profile-btn"
                                onclick="document.getElementById('profile-pic-input').click();">
                            <i class="fa-solid fa-camera"></i>
                        </button>
                    </form>
                </div>
                <div class="detail-overlay_texts">
                    <h3 class="detail-full-name">{{ profile.user.get_full_name }}</h3>
                    <h5 class="detail-profession">{{ profile.profession }}</h5>
                </div>
            </div>
            <div class="detail-buttons">
                <button class="detail-message-btn">
                    <img src="{% static 'images/message.svg' %}" alt="message" class="detail-message-icon">
                </button>
                <button class="detail-follow-btn">Follow</button>
                <button class="detail-schelude-btn">Schedule a meeting</button>
            </div>
        </section>
        <div class="profile-detail-footer">
            {# aside #}
            <aside class="detail-about">
                <h2 class="about-title">About</h2>
                <ul class="about-list">
                    <li>
                        <i class="fa-solid fa-user"></i>
                        <span>{{ profile.gender }}</span>
                    </li>
                    <li>
                        <i class="fa-solid fa-cake-candles"></i>
                        <span>Born {{ profile.birth_date|date:"F j, Y" }}</span>
                    </li>
                    <li>
                        <i class="fa-solid fa-envelope"></i>
                        <span>{{ profile.user.email }}</span>
                    </li>
                    <li>
                        <i class="fa-solid fa-phone"></i>
                        <span>{{ profile.phone }}</span>
                    </li>
                </ul>
            </aside>
            {#posts#}
            <div class="detail-posts">
                <h2 class="posts-title">Posts</h2>
                <div class="form-box">
                    <h4 class="form-box-title">Create Post</h4>
                    {# ფორმა პოსტისთვის #}
                    <form method="post" enctype="multipart/form-data" class="post-form">
                        {% csrf_token %}
                        {{ form.non_field_errors }}

                        {% if editing_post %}
                            <input type="hidden" name="post_id" value="{{ editing_post.id }}">
                            <h4>Editing Post</h4>
                        {% endif %}

                        <div class="form-section">
                            {{ form.caption.errors }}
                            {{ form.caption }}
                        </div>

                        <label for="{{ form.image.id_for_label }}" class="image-upload-label">
                            <div class="image-upload-box">
                                <img src="{% static 'images/upload.svg' %}" alt="Upload Icon" class="upload-icon"/>
                                <span>Add Photo</span>
                            </div>
                            {{ form.image.errors }}
                            {{ form.image }}
                        </label>

                        <div class="form-buttons">
                            <button type="button" class="cancel-btn" onclick="clearPostForm()">Cancel</button>
                            <button type="submit" class="publish-btn">Publish</button>
                        </div>
                    </form>
                </div>
                {#პოსტი#}
                <div class="posts">
                    {% for post in posts %}
                        <div class="post-card">

                            <div class="posts-header">
                                <div class="posts-header-left">
                                    <img src="{{ profile.profile_pic.url }}" alt="Profile Picture"
                                         class="posts-profile-picture">
                                    <div>
                                        <h3 class="posts-full-name">{{ profile.user.get_full_name }}</h3>
                                        <p class="posts-create-date">{{ post.created_at|timesince }} ago</p>
                                    </div>
                                </div>
                                {#Delete/Edit #}
                                <div class="posts-header-right">
                                    <button class="ellipsis-btn" onclick="toggleMenu(this)">
                                        <i class="fa-solid fa-ellipsis"></i>
                                    </button>

                                    <div class="post-menu" style="display: none;">
                                        <form method="post" action="{% url 'profiles:delete_post' profile.pk post.pk %}"
                                              onsubmit="return confirm('Are you sure?');">
                                            {% csrf_token %}
                                            <button type="submit" class="menu-item delete">Delete</button>
                                        </form>
                                        <a href="{% url 'profiles:edit_post' profile.pk post.pk %}"
                                           class="menu-item edit">Edit</a>
                                    </div>
                                </div>

                            </div>

                            <div class="posts-footer">
                                {% if post.image %}
                                    <img src="{{ post.image.url }}" alt="Post image" class="posts-cover">
                                {% endif %}
                                <p class="caption">{{ post.caption }}</p>
                                <div class="heart-time">
                                    <p>
                                        <i class="fa-regular fa-heart"></i>
                                        <span> {{ post.likes }}</span>
                                    </p>
                                    <p>
                                        <i class="fa-regular fa-comment"></i>
                                        <span>{{ post.comments }}</span>
                                    </p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

userprofile_project/profiles/templates/user_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Users{% endblock %}

{% block content %}
    <h1 class="users-title">All Users</h1>
    <div class="profile-grid">
        {% for profile in page_obj %}
            <div class="profile-card">
                <a href="{% url 'profiles:profile_detail' profile.pk %}">
                    <img src="{{ profile.avatar.url }}" alt="{{ profile.user.username }}'s avatar">
                    <h3>{{ profile.user.get_full_name|default:profile.user.username }}</h3>
                    <p>{{ profile.profession }}</p>
                </a>
            </div>
        {% endfor %}
    </div>
    <!-- Pagination controls -->
    <div class="pagination">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current-page">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
    </div>

{% endblock %}

userprofile_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}User Profile{% endblock %}</title>

    <!-- favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'images/logo.png' %}">

    <!-- main styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/085bce8105.js" crossorigin="anonymous"></script>

    {% block extra_head %}{% endblock %}
</head>
<body>
<div class="page-wrapper">
    <header>
        <a href="{% url 'profiles:user_list' %}" class="logo-link">
            <i class="fa-solid fa-users logo"></i>
        </a>
        <nav class="navbar">
            <ul class="menu">
                <li>
                    {# აქტიურია მხოლოდ users გვერდზე #}
                    <i class="fa-solid fa-user {% if request.resolver_match.url_name == 'user_list' %}active{% endif %}"></i>
                    <a href="{% url 'profiles:user_list' %}"
                       class="menu-link {% if request.resolver_match.url_name == 'user_list' %}active{% endif %}">Users</a>
                </li>

                {% if request.user.is_authenticated and request.user.profile %}
                    <li>
                        <i class="fa-solid fa-id-badge"></i>
                        <a href="{% url 'profiles:profile_detail' request.user.profile.pk %}"
                           class="menu-link">Profile</a>
                    </li>
                {% endif %}
                <li>
                    <i class="fa-solid fa-chart-line"></i>
                    <a href="#" class="menu-link">Dashboard</a>
                </li>
                <li>
                    <i class="fa-solid fa-gear"></i>
                    <a href="#" class="menu-link">Settings</a>
                </li>
                <li>
                    <i class="fa-solid fa-bell"></i>
                    <a href="#" class="menu-link">Notifications</a>
                </li>
                <li>
                    <i class="fa-solid fa-circle-question"></i>
                    <a href="#" class="menu-link">Help</a>
                </li>
                <li>
                    <i class="fa-solid fa-right-from-bracket"></i>
                    <a href="#" class="menu-link">Log out</a>
                </li>
            </ul>
        </nav>
    </header>

    <div class="main-container">
        {% block content %}
            <!-- content -->
        {% endblock %}
    </div>
</div>

<script src="{% static 'js/post.js' %}"></script>
</body>
</html>